// ─── Schemas ──────────────────────────────────────────────────────────────────

// Legacy OCR/input schemas (backwards compatible)
export {
  ingredientSchema,
  recipeStepSchema,
  recipeImageSchema,
  slugSchema,
  recipeSchema,
  recipeCreateSchema,
  recipeUpdateSchema,
} from './schemas/recipe.js';

// Full DB schemas
export {
  uuidSchema,
  dbSlugSchema,
  timestampSchema,
  tagTypeSchema,
  difficultySchema,
  sourceTypeSchema,
  storeSchema,
  ocrStatusSchema,
  categorySchema,
  categoryCreateSchema,
  categoryUpdateSchema,
  tagSchema,
  tagCreateSchema,
  tagUpdateSchema,
  ingredientDbSchema,
  ingredientDbCreateSchema,
  ingredientDbUpdateSchema,
  ingredientSeasonSchema,
  ingredientSeasonCreateSchema,
  recipeDbSchema,
  recipeDbCreateSchema,
  recipeDbUpdateSchema,
  recipeIngredientSchema,
  recipeIngredientCreateSchema,
  recipeStepDbSchema,
  recipeStepDbCreateSchema,
  recipeTagSchema,
  storeProductSchema,
  storeProductCreateSchema,
  pantryItemSchema,
  pantryItemCreateSchema,
  shoppingListSchema,
  shoppingListCreateSchema,
  shoppingListItemSchema,
  shoppingListItemCreateSchema,
  recipeFavoriteSchema,
  ocrImportSchema,
  ocrImportCreateSchema,
  ocrImportUpdateSchema,
} from './schemas/index.js';

// ─── Types ────────────────────────────────────────────────────────────────────

// Legacy OCR/input types (backwards compatible)
export type {
  Ingredient,
  RecipeStep,
  RecipeImage,
  Recipe,
  RecipeCreate,
  RecipeUpdate,
} from './types/recipe.js';

// Full DB types
export type {
  TagType,
  Difficulty,
  SourceType,
  Store,
  OcrStatus,
  Category,
  CategoryCreate,
  CategoryUpdate,
  Tag,
  TagCreate,
  TagUpdate,
  IngredientDb,
  IngredientDbCreate,
  IngredientDbUpdate,
  IngredientSeason,
  IngredientSeasonCreate,
  RecipeDb,
  RecipeDbCreate,
  RecipeDbUpdate,
  RecipeIngredient,
  RecipeIngredientCreate,
  RecipeStepDb,
  RecipeStepDbCreate,
  RecipeTag,
  StoreProduct,
  StoreProductCreate,
  PantryItem,
  PantryItemCreate,
  ShoppingList,
  ShoppingListCreate,
  ShoppingListItem,
  ShoppingListItemCreate,
  RecipeFavorite,
  OcrImport,
  OcrImportCreate,
  OcrImportUpdate,
  RecipeWithRelations,
  RecipeSummary,
} from './types/index.js';
